#pragma once

#include <S31/Log/S31Only/SecurityLogger.h>

/**
 * @brief Log a security message with given event code (from Doors).
 * \ingroup S31Log
 */
#define S31_SECURITY_LOG(...) ::S31::Log::Impl::writeSecurityStreamLogMessage(__FILE__, __LINE__, ::DFL::Log::SecurityState::Event, __VA_ARGS__)

/**
 * @brief Log and trap a security message with given event code (from Doors).
 * @details In addition to the log message a trap information (e.g., SNMP trap)
 * should generated by the log backend.
 * \ingroup S31Log
 */
#define S31_SECURITY_LOG_AND_TRAP(...) ::S31::Log::Impl::writeSecurityStreamLogMessage(__FILE__, __LINE__, ::DFL::Log::SecurityState::Trap, __VA_ARGS__)
