#pragma once

#include <S31/S31CoreExImp.h>

namespace DFL
{
namespace Mdib
{
class Handle;
}
namespace Locale
{
class Utf8;
}
}

namespace S31::Sdc
{

/**
 * @brief Internal helper class to generate unique %MDIB handle names.
 *
 * \ingroup S31SdcDevice
 */
class S31_CORE_EXPIMP HandleGenerator
{
    public:
        /**
         * @brief Creates a new handle name.
         * @details The handle name is generated by concatenating the given prefix 'MDIBH' with an atomically incremented counter.
         * @return the unique handle name.
         */
        static DFL::Mdib::Handle next();

        /**
         * @brief Creates a new handle name.
         * @details The handle name is generated by concatenating the given prefix with an atomically incremented counter.
         * @param prefix A prefix for the handle name.
         * @return the unique handle name.
         */
        static DFL::Mdib::Handle nextWithPrefix(const DFL::Locale::Utf8& prefix);

        /**
         * @brief Creates a new handle name.
         * @details The handle name is generated by concatenating the given prefix with an atomically incremented counter.
         * @param postfix A postfix for the handle name.
         * @return the unique handle name.
         */
        static DFL::Mdib::Handle nextWithPostfix(const DFL::Locale::Utf8& postfix);
};

}
