/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Context/EnsembleContextState.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param ensembleContextState @ref DFL::Mdib::EnsembleContextState value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const EnsembleContextState& ensembleContextState)
{
    vis(ensembleContextState.category());
    vis(ensembleContextState.contextAssociation());
    vis(ensembleContextState.bindingMdibVersion());
    vis(ensembleContextState.unbindingMdibVersion());
    vis(ensembleContextState.bindingStartTime());
    vis(ensembleContextState.bindingEndTime());
    vis(ensembleContextState.validators());
    vis(ensembleContextState.identifications());
    vis(ensembleContextState.extensions());
}
}
}
}
