/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Context/LocationContextState.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param locationContextState @ref DFL::Mdib::LocationContextState value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const LocationContextState& locationContextState)
{
    vis(locationContextState.category());
    vis(locationContextState.contextAssociation());
    vis(locationContextState.bindingMdibVersion());
    vis(locationContextState.unbindingMdibVersion());
    vis(locationContextState.bindingStartTime());
    vis(locationContextState.bindingEndTime());
    vis(locationContextState.validators());
    vis(locationContextState.identifications());
    vis(locationContextState.locationDetail());
    vis(locationContextState.extensions());
}
}
}
}
