/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Component/MdsState.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param mdsState @ref DFL::Mdib::MdsState value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const MdsState& mdsState)
{
    vis(mdsState.activationState());
    vis(mdsState.operatingHours());
    vis(mdsState.operatingCycles());
    vis(mdsState.calibrationInfo());
    vis(mdsState.nextCalibrationInfo());
    vis(mdsState.physicalConnector());
    vis(mdsState.lang());
    vis(mdsState.operatingMode());
    vis(mdsState.operatingJurisdiction());
    vis(mdsState.extensions());
}
}
}
}
