/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Component/PhysicalConnectorInfo.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param physicalConnectorInfo @ref DFL::Mdib::PhysicalConnectorInfo value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const PhysicalConnectorInfo& physicalConnectorInfo)
{
    vis(physicalConnectorInfo.number());
    vis(physicalConnectorInfo.labels());
    vis(physicalConnectorInfo.extensions());
}
}
}
}
