/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Component/VmdDescriptor.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param vmdDescriptor @ref DFL::Mdib::VmdDescriptor value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const VmdDescriptor& vmdDescriptor)
{
    vis(vmdDescriptor.safetyClassification());
    vis(vmdDescriptor.type());
    vis(vmdDescriptor.productionSpecifications());
    vis(vmdDescriptor.approvedJurisdictions());
    vis(vmdDescriptor.extensions());
}
}
}
}
