/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Alert/AlertSystemDescriptor.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param alertSystemDescriptor @ref DFL::Mdib::AlertSystemDescriptor value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const AlertSystemDescriptor& alertSystemDescriptor)
{
    vis(alertSystemDescriptor.safetyClassification());
    vis(alertSystemDescriptor.type());
    vis(alertSystemDescriptor.maxPhysiologicalAlarmListEntries());
    vis(alertSystemDescriptor.maxTechnicalAlarmListEntries());
    vis(alertSystemDescriptor.selfCheckPeriod());
    vis(alertSystemDescriptor.extensions());
}
}
}
}
