/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <memory>
#include <boost/optional.hpp>
#include <Framework/Mdib/Private/ExpImp.h>
#include <Framework/Mdib/Private/Utils/SmartPtrTypes.h>
#include <Framework/Utils/Public/NotNull.h>

#include <Framework/Mdib/Public/Model/Context/EnsembleContextDescriptor.h>

namespace DFL
{
namespace Mdib
{

/**
 * @brief Builder with fluent interface for @ref EnsembleContextDescriptor
 * @ingroup Mdib
 */
class EnsembleContextDescriptorBuilder
{
    public:
        /// @brief Typedef to the immutable @ref EnsembleContextDescriptor
        using BuiltType = EnsembleContextDescriptor;

        /// @brief Builder based on given immutable @ref EnsembleContextDescriptor
        explicit EnsembleContextDescriptorBuilder(const EnsembleContextDescriptor& ensembleContextDescriptor=EnsembleContextDescriptor());

        /// @brief Builder based on given immutable @ref EnsembleContextDescriptor
        explicit EnsembleContextDescriptorBuilder(const DFL::NotNull<SharedPtr<EnsembleContextDescriptor>>& ensembleContextDescriptor);

        /// @brief Overwrite all values with given immutable @ref EnsembleContextDescriptor
        EnsembleContextDescriptorBuilder& operator=(const EnsembleContextDescriptor& ensembleContextDescriptor);

        /// @brief Explicit conversion to immutable @ref EnsembleContextDescriptor
        EnsembleContextDescriptor build() const;

        /// @brief Test whether the builder differs from the immutable @ref EnsembleContextDescriptor
        bool isChanged(const EnsembleContextDescriptor& base) const;

        /// @brief Setter for safetyClassification
        /// @{
        EnsembleContextDescriptorBuilder& safetyClassification(SafetyClassification safetyClassification);
        /// @}

        /// @brief Setter for type
        /// @{
        EnsembleContextDescriptorBuilder& type(const boost::optional<CodedValue>& type);
        EnsembleContextDescriptorBuilder& type(boost::optional<CodedValue>&& type);
        /// @}

        /// @brief Setter for extensions
        /// @{
        EnsembleContextDescriptorBuilder& extensions(const ExtensionTypes& extensions);
        EnsembleContextDescriptorBuilder& extensions(ExtensionTypes&& extensions);
        /// @}

        /// @brief Getter for safetyClassification
        /// @{
        SafetyClassification& safetyClassification();
        SafetyClassification safetyClassification() const;
        /// @}

        /// @brief Getter for type
        /// @{
        boost::optional<CodedValue>& type();
        const boost::optional<CodedValue>& type() const;
        /// @}

        /// @brief Getter for extensions
        /// @{
        ExtensionTypes& extensions();
        const ExtensionTypes& extensions() const;
        /// @}

    private:
        SafetyClassification m_safetyClassification;
        boost::optional<CodedValue> m_type;
        ExtensionTypes m_extensions;
};

/**
 * @brief Equal operator compares all members
 * @ingroup Mdib
 */
/// @{
DFL_MDIB_EXPIMP bool operator==(const EnsembleContextDescriptor& lhs, const EnsembleContextDescriptor& rhs);
DFL_MDIB_EXPIMP bool operator==(const EnsembleContextDescriptorBuilder& lhs, const EnsembleContextDescriptorBuilder& rhs);
DFL_MDIB_EXPIMP bool operator==(const EnsembleContextDescriptorBuilder& lhs, const EnsembleContextDescriptor& rhs);
bool operator==(const EnsembleContextDescriptor& lhs, const EnsembleContextDescriptorBuilder& rhs);
/// @}

/**
 * @brief Not equal operator compares all members
 * @ingroup Mdib
 */
/// @{
DFL_MDIB_EXPIMP bool operator!=(const EnsembleContextDescriptor& lhs, const EnsembleContextDescriptor& rhs);
bool operator!=(const EnsembleContextDescriptorBuilder& lhs, const EnsembleContextDescriptorBuilder& rhs);
bool operator!=(const EnsembleContextDescriptor& lhs, const EnsembleContextDescriptorBuilder& rhs);
bool operator!=(const EnsembleContextDescriptorBuilder& lhs, const EnsembleContextDescriptor& rhs);
/// @}

/**
 * @brief Factory function to create %Builder based on given immutable @ref EnsembleContextDescriptor
 * @ingroup Mdib
 */
/// @{
EnsembleContextDescriptorBuilder getBuilder(const EnsembleContextDescriptor& ensembleContextDescriptor);
EnsembleContextDescriptorBuilder getBuilder(const DFL::NotNull<SharedPtr<EnsembleContextDescriptor>>& ensembleContextDescriptor);
/// @}

/**
 * @brief Helper function throws runtime_error in case of a not equal member
 * @ingroup Mdib
 */
DFL_MDIB_EXPIMP void assertEqual(const EnsembleContextDescriptor& lhs, const EnsembleContextDescriptor& rhs);

inline EnsembleContextDescriptorBuilder::EnsembleContextDescriptorBuilder(const EnsembleContextDescriptor& ensembleContextDescriptor) :
    m_safetyClassification(ensembleContextDescriptor.safetyClassification()),
    m_type(ensembleContextDescriptor.type()),
    m_extensions(ensembleContextDescriptor.extensions())
{
}

inline EnsembleContextDescriptorBuilder::EnsembleContextDescriptorBuilder(const DFL::NotNull<SharedPtr<EnsembleContextDescriptor>>& ensembleContextDescriptor) :
    m_safetyClassification(ensembleContextDescriptor->safetyClassification()),
    m_type(ensembleContextDescriptor->type()),
    m_extensions(ensembleContextDescriptor->extensions())
{
}

inline EnsembleContextDescriptorBuilder& EnsembleContextDescriptorBuilder::operator=(const EnsembleContextDescriptor& ensembleContextDescriptor)
{
    m_safetyClassification = ensembleContextDescriptor.safetyClassification();
    m_type = ensembleContextDescriptor.type();
    m_extensions = ensembleContextDescriptor.extensions();
    return *this;
}

inline EnsembleContextDescriptor EnsembleContextDescriptorBuilder::build() const
{
    // NOLINTNEXTLINE(modernize-return-braced-init-list)
    return EnsembleContextDescriptor(m_safetyClassification, m_type, m_extensions);
}

inline bool EnsembleContextDescriptorBuilder::isChanged(const EnsembleContextDescriptor& base) const
{
    return *this != base;
}

inline EnsembleContextDescriptorBuilder& EnsembleContextDescriptorBuilder::safetyClassification(SafetyClassification safetyClassification)
{
    m_safetyClassification = safetyClassification;
    return *this;
}

inline SafetyClassification& EnsembleContextDescriptorBuilder::safetyClassification()
{
    return m_safetyClassification;
}

inline SafetyClassification EnsembleContextDescriptorBuilder::safetyClassification() const
{
    return m_safetyClassification;
}

inline EnsembleContextDescriptorBuilder& EnsembleContextDescriptorBuilder::type(const boost::optional<CodedValue>& type)
{
    m_type = type;
    return *this;
}

inline EnsembleContextDescriptorBuilder& EnsembleContextDescriptorBuilder::type(boost::optional<CodedValue>&& type)
{
    m_type = std::move(type);
    return *this;
}

inline boost::optional<CodedValue>& EnsembleContextDescriptorBuilder::type()
{
    return m_type;
}

inline const boost::optional<CodedValue>& EnsembleContextDescriptorBuilder::type() const
{
    return m_type;
}

inline EnsembleContextDescriptorBuilder& EnsembleContextDescriptorBuilder::extensions(const ExtensionTypes& extensions)
{
    m_extensions = extensions;
    return *this;
}

inline EnsembleContextDescriptorBuilder& EnsembleContextDescriptorBuilder::extensions(ExtensionTypes&& extensions)
{
    m_extensions = std::move(extensions);
    return *this;
}

inline ExtensionTypes& EnsembleContextDescriptorBuilder::extensions()
{
    return m_extensions;
}

inline const ExtensionTypes& EnsembleContextDescriptorBuilder::extensions() const
{
    return m_extensions;
}

inline bool operator==(const EnsembleContextDescriptor& lhs, const EnsembleContextDescriptorBuilder& rhs)
{
    return rhs == lhs;
}

inline bool operator!=(const EnsembleContextDescriptorBuilder& lhs, const EnsembleContextDescriptorBuilder& rhs)
{
    return !(lhs == rhs);
}

inline bool operator!=(const EnsembleContextDescriptor& lhs, const EnsembleContextDescriptorBuilder& rhs)
{
    return !(lhs == rhs);
}

inline bool operator!=(const EnsembleContextDescriptorBuilder& lhs, const EnsembleContextDescriptor& rhs)
{
    return !(lhs == rhs);
}

inline EnsembleContextDescriptorBuilder getBuilder(const EnsembleContextDescriptor& ensembleContextDescriptor)
{
    return EnsembleContextDescriptorBuilder(ensembleContextDescriptor);
}

inline EnsembleContextDescriptorBuilder getBuilder(const DFL::NotNull<SharedPtr<EnsembleContextDescriptor>>& ensembleContextDescriptor)
{
    return EnsembleContextDescriptorBuilder(ensembleContextDescriptor);
}

}
}
