/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <memory>
#include <boost/optional.hpp>
#include <Framework/Mdib/Private/ExpImp.h>
#include <Framework/Mdib/Private/Utils/SmartPtrTypes.h>
#include <Framework/Utils/Public/NotNull.h>

#include <Framework/Mdib/Public/Model/Context/PatientContextDescriptor.h>

namespace DFL
{
namespace Mdib
{

/**
 * @brief Builder with fluent interface for @ref PatientContextDescriptor
 * @ingroup Mdib
 */
class PatientContextDescriptorBuilder
{
    public:
        /// @brief Typedef to the immutable @ref PatientContextDescriptor
        using BuiltType = PatientContextDescriptor;

        /// @brief Builder based on given immutable @ref PatientContextDescriptor
        explicit PatientContextDescriptorBuilder(const PatientContextDescriptor& patientContextDescriptor=PatientContextDescriptor());

        /// @brief Builder based on given immutable @ref PatientContextDescriptor
        explicit PatientContextDescriptorBuilder(const DFL::NotNull<SharedPtr<PatientContextDescriptor>>& patientContextDescriptor);

        /// @brief Overwrite all values with given immutable @ref PatientContextDescriptor
        PatientContextDescriptorBuilder& operator=(const PatientContextDescriptor& patientContextDescriptor);

        /// @brief Explicit conversion to immutable @ref PatientContextDescriptor
        PatientContextDescriptor build() const;

        /// @brief Test whether the builder differs from the immutable @ref PatientContextDescriptor
        bool isChanged(const PatientContextDescriptor& base) const;

        /// @brief Setter for safetyClassification
        /// @{
        PatientContextDescriptorBuilder& safetyClassification(SafetyClassification safetyClassification);
        /// @}

        /// @brief Setter for type
        /// @{
        PatientContextDescriptorBuilder& type(const boost::optional<CodedValue>& type);
        PatientContextDescriptorBuilder& type(boost::optional<CodedValue>&& type);
        /// @}

        /// @brief Setter for extensions
        /// @{
        PatientContextDescriptorBuilder& extensions(const ExtensionTypes& extensions);
        PatientContextDescriptorBuilder& extensions(ExtensionTypes&& extensions);
        /// @}

        /// @brief Getter for safetyClassification
        /// @{
        SafetyClassification& safetyClassification();
        SafetyClassification safetyClassification() const;
        /// @}

        /// @brief Getter for type
        /// @{
        boost::optional<CodedValue>& type();
        const boost::optional<CodedValue>& type() const;
        /// @}

        /// @brief Getter for extensions
        /// @{
        ExtensionTypes& extensions();
        const ExtensionTypes& extensions() const;
        /// @}

    private:
        SafetyClassification m_safetyClassification;
        boost::optional<CodedValue> m_type;
        ExtensionTypes m_extensions;
};

/**
 * @brief Equal operator compares all members
 * @ingroup Mdib
 */
/// @{
DFL_MDIB_EXPIMP bool operator==(const PatientContextDescriptor& lhs, const PatientContextDescriptor& rhs);
DFL_MDIB_EXPIMP bool operator==(const PatientContextDescriptorBuilder& lhs, const PatientContextDescriptorBuilder& rhs);
DFL_MDIB_EXPIMP bool operator==(const PatientContextDescriptorBuilder& lhs, const PatientContextDescriptor& rhs);
bool operator==(const PatientContextDescriptor& lhs, const PatientContextDescriptorBuilder& rhs);
/// @}

/**
 * @brief Not equal operator compares all members
 * @ingroup Mdib
 */
/// @{
DFL_MDIB_EXPIMP bool operator!=(const PatientContextDescriptor& lhs, const PatientContextDescriptor& rhs);
bool operator!=(const PatientContextDescriptorBuilder& lhs, const PatientContextDescriptorBuilder& rhs);
bool operator!=(const PatientContextDescriptor& lhs, const PatientContextDescriptorBuilder& rhs);
bool operator!=(const PatientContextDescriptorBuilder& lhs, const PatientContextDescriptor& rhs);
/// @}

/**
 * @brief Factory function to create %Builder based on given immutable @ref PatientContextDescriptor
 * @ingroup Mdib
 */
/// @{
PatientContextDescriptorBuilder getBuilder(const PatientContextDescriptor& patientContextDescriptor);
PatientContextDescriptorBuilder getBuilder(const DFL::NotNull<SharedPtr<PatientContextDescriptor>>& patientContextDescriptor);
/// @}

/**
 * @brief Helper function throws runtime_error in case of a not equal member
 * @ingroup Mdib
 */
DFL_MDIB_EXPIMP void assertEqual(const PatientContextDescriptor& lhs, const PatientContextDescriptor& rhs);

inline PatientContextDescriptorBuilder::PatientContextDescriptorBuilder(const PatientContextDescriptor& patientContextDescriptor) :
    m_safetyClassification(patientContextDescriptor.safetyClassification()),
    m_type(patientContextDescriptor.type()),
    m_extensions(patientContextDescriptor.extensions())
{
}

inline PatientContextDescriptorBuilder::PatientContextDescriptorBuilder(const DFL::NotNull<SharedPtr<PatientContextDescriptor>>& patientContextDescriptor) :
    m_safetyClassification(patientContextDescriptor->safetyClassification()),
    m_type(patientContextDescriptor->type()),
    m_extensions(patientContextDescriptor->extensions())
{
}

inline PatientContextDescriptorBuilder& PatientContextDescriptorBuilder::operator=(const PatientContextDescriptor& patientContextDescriptor)
{
    m_safetyClassification = patientContextDescriptor.safetyClassification();
    m_type = patientContextDescriptor.type();
    m_extensions = patientContextDescriptor.extensions();
    return *this;
}

inline PatientContextDescriptor PatientContextDescriptorBuilder::build() const
{
    // NOLINTNEXTLINE(modernize-return-braced-init-list)
    return PatientContextDescriptor(m_safetyClassification, m_type, m_extensions);
}

inline bool PatientContextDescriptorBuilder::isChanged(const PatientContextDescriptor& base) const
{
    return *this != base;
}

inline PatientContextDescriptorBuilder& PatientContextDescriptorBuilder::safetyClassification(SafetyClassification safetyClassification)
{
    m_safetyClassification = safetyClassification;
    return *this;
}

inline SafetyClassification& PatientContextDescriptorBuilder::safetyClassification()
{
    return m_safetyClassification;
}

inline SafetyClassification PatientContextDescriptorBuilder::safetyClassification() const
{
    return m_safetyClassification;
}

inline PatientContextDescriptorBuilder& PatientContextDescriptorBuilder::type(const boost::optional<CodedValue>& type)
{
    m_type = type;
    return *this;
}

inline PatientContextDescriptorBuilder& PatientContextDescriptorBuilder::type(boost::optional<CodedValue>&& type)
{
    m_type = std::move(type);
    return *this;
}

inline boost::optional<CodedValue>& PatientContextDescriptorBuilder::type()
{
    return m_type;
}

inline const boost::optional<CodedValue>& PatientContextDescriptorBuilder::type() const
{
    return m_type;
}

inline PatientContextDescriptorBuilder& PatientContextDescriptorBuilder::extensions(const ExtensionTypes& extensions)
{
    m_extensions = extensions;
    return *this;
}

inline PatientContextDescriptorBuilder& PatientContextDescriptorBuilder::extensions(ExtensionTypes&& extensions)
{
    m_extensions = std::move(extensions);
    return *this;
}

inline ExtensionTypes& PatientContextDescriptorBuilder::extensions()
{
    return m_extensions;
}

inline const ExtensionTypes& PatientContextDescriptorBuilder::extensions() const
{
    return m_extensions;
}

inline bool operator==(const PatientContextDescriptor& lhs, const PatientContextDescriptorBuilder& rhs)
{
    return rhs == lhs;
}

inline bool operator!=(const PatientContextDescriptorBuilder& lhs, const PatientContextDescriptorBuilder& rhs)
{
    return !(lhs == rhs);
}

inline bool operator!=(const PatientContextDescriptor& lhs, const PatientContextDescriptorBuilder& rhs)
{
    return !(lhs == rhs);
}

inline bool operator!=(const PatientContextDescriptorBuilder& lhs, const PatientContextDescriptor& rhs)
{
    return !(lhs == rhs);
}

inline PatientContextDescriptorBuilder getBuilder(const PatientContextDescriptor& patientContextDescriptor)
{
    return PatientContextDescriptorBuilder(patientContextDescriptor);
}

inline PatientContextDescriptorBuilder getBuilder(const DFL::NotNull<SharedPtr<PatientContextDescriptor>>& patientContextDescriptor)
{
    return PatientContextDescriptorBuilder(patientContextDescriptor);
}

}
}
