/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Component/MdsDescriptor.h>
#include <Framework/Mdib/Public/Model/CodedValueSerialize.h>
#include <Framework/Mdib/Public/Model/Component/MetaDataSerialize.h>
#include <Framework/Mdib/Public/Model/Component/ProductionSpecificationSerialize.h>
#include <Framework/Mdib/Public/Model/ExtensionTypeSerialize.h>
#include <Framework/Mdib/Public/Model/InstanceIdentifierSerialize.h>
#include <Framework/Utils/Public/SerializationHelper.h>

#include <boost/serialization/nvp.hpp>
#include <boost/serialization/split_free.hpp>
#include <boost/serialization/version.hpp>
#include <boost/serialization/optional.hpp>
#include <boost/serialization/vector.hpp>

#include <utility>

BOOST_SERIALIZATION_SPLIT_FREE(::DFL::Mdib::MdsDescriptor)

BOOST_CLASS_VERSION(::DFL::Mdib::MdsDescriptor, 0)

BOOST_CLASS_TRACKING(::DFL::Mdib::MdsDescriptor, boost::serialization::track_never)

namespace boost
{
namespace serialization
{
/**
 * @brief Support for Boost Serialization.
 * @ingroup Mdib
 */
template<class Archive>
void save(Archive& ar, const ::DFL::Mdib::MdsDescriptor& src, const unsigned int /*fileVersion*/)
{
    const auto& safetyClassification = src.safetyClassification();
    ar & make_nvp("SafetyClassification", safetyClassification);

    const auto& type = src.type();
    DFL::Serialization::saveNvpOptional(ar, "Type", type);

    const auto& productionSpecifications = src.productionSpecifications();
    ar & make_nvp("ProductionSpecifications", productionSpecifications);

    const auto& metaData = src.metaData();
    ar & make_nvp("MetaData", metaData);

    const auto& approvedJurisdictions = src.approvedJurisdictions();
    ar & make_nvp("ApprovedJurisdictions", approvedJurisdictions);

    const auto& extensions = src.extensions();
    ar & make_nvp("Extensions", extensions);
}

/**
 * @brief Support for Boost Serialization.
 * @ingroup Mdib
 */
template<class Archive>
void load_construct_data(Archive& ar, ::DFL::Mdib::MdsDescriptor* dst, const unsigned int /*version*/)
{
    ::DFL::Mdib::SafetyClassification safetyClassification{};
    ar & make_nvp("SafetyClassification", safetyClassification);

    boost::optional<::DFL::Mdib::CodedValue> type{};
    DFL::Serialization::loadNvpOptional(ar, "Type", type);

    ::DFL::Mdib::ProductionSpecifications productionSpecifications{};
    ar & make_nvp("ProductionSpecifications", productionSpecifications);

    boost::optional<::DFL::Mdib::MetaData> metaData{};
    ar & make_nvp("MetaData", metaData);

    boost::optional<::DFL::Mdib::InstanceIdentifiers> approvedJurisdictions{};
    ar & make_nvp("ApprovedJurisdictions", approvedJurisdictions);

    ::DFL::Mdib::ExtensionTypes extensions{};
    ar & make_nvp("Extensions", extensions);

    ::new(dst) ::DFL::Mdib::MdsDescriptor(
        safetyClassification,
        std::move(type),
        std::move(productionSpecifications),
        std::move(metaData),
        std::move(approvedJurisdictions),
        std::move(extensions));
}

/**
 * @brief Support for Boost Serialization.
 * @ingroup Mdib
 */
template<class Archive>
void load(Archive& /*ar*/, ::DFL::Mdib::MdsDescriptor& /*dst*/, const unsigned int /*version*/)
{
}

}
}
