/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Component/ScoState.h>
#include <Framework/Chrono/Public/DurationSerialize.h>
#include <Framework/Mdib/Public/Model/Component/CalibrationInfoSerialize.h>
#include <Framework/Mdib/Public/Model/Component/PhysicalConnectorInfoSerialize.h>
#include <Framework/Mdib/Public/Model/ExtensionTypeSerialize.h>
#include <Framework/Mdib/Public/Model/HandleSerialize.h>
#include <Framework/Mdib/Public/Model/Operation/OperationGroupSerialize.h>
#include <Framework/Utils/Public/SerializationHelper.h>

#include <boost/serialization/nvp.hpp>
#include <boost/serialization/split_free.hpp>
#include <boost/serialization/version.hpp>
#include <boost/serialization/optional.hpp>
#include <boost/serialization/vector.hpp>

#include <utility>

BOOST_SERIALIZATION_SPLIT_FREE(::DFL::Mdib::ScoState)

BOOST_CLASS_VERSION(::DFL::Mdib::ScoState, 0)

BOOST_CLASS_TRACKING(::DFL::Mdib::ScoState, boost::serialization::track_never)

namespace boost
{
namespace serialization
{
/**
 * @brief Support for Boost Serialization.
 * @ingroup Mdib
 */
template<class Archive>
void save(Archive& ar, const ::DFL::Mdib::ScoState& src, const unsigned int /*fileVersion*/)
{
    const auto& activationState = src.activationState();
    ar & make_nvp("ActivationState", activationState);

    const auto& operatingHours = src.operatingHours();
    ar & make_nvp("OperatingHours", operatingHours);

    const auto& operatingCycles = src.operatingCycles();
    ar & make_nvp("OperatingCycles", operatingCycles);

    const auto& calibrationInfo = src.calibrationInfo();
    ar & make_nvp("CalibrationInfo", calibrationInfo);

    const auto& nextCalibrationInfo = src.nextCalibrationInfo();
    ar & make_nvp("NextCalibrationInfo", nextCalibrationInfo);

    const auto& physicalConnector = src.physicalConnector();
    ar & make_nvp("PhysicalConnector", physicalConnector);

    const auto& invocationRequested = src.invocationRequested();
    ar & make_nvp("InvocationRequested", invocationRequested);

    const auto& invocationRequired = src.invocationRequired();
    ar & make_nvp("InvocationRequired", invocationRequired);

    const auto& operationGroups = src.operationGroups();
    ar & make_nvp("OperationGroups", operationGroups);

    const auto& extensions = src.extensions();
    ar & make_nvp("Extensions", extensions);
}

/**
 * @brief Support for Boost Serialization.
 * @ingroup Mdib
 */
template<class Archive>
void load_construct_data(Archive& ar, ::DFL::Mdib::ScoState* dst, const unsigned int /*version*/)
{
    ::DFL::Mdib::ComponentActivation activationState{};
    ar & make_nvp("ActivationState", activationState);

    boost::optional<::DFL::Chrono::Hours> operatingHours{};
    ar & make_nvp("OperatingHours", operatingHours);

    boost::optional<::DFL::Mdib::OperatingCycles> operatingCycles{};
    ar & make_nvp("OperatingCycles", operatingCycles);

    boost::optional<::DFL::Mdib::CalibrationInfo> calibrationInfo{};
    ar & make_nvp("CalibrationInfo", calibrationInfo);

    boost::optional<::DFL::Mdib::CalibrationInfo> nextCalibrationInfo{};
    ar & make_nvp("NextCalibrationInfo", nextCalibrationInfo);

    boost::optional<::DFL::Mdib::PhysicalConnectorInfo> physicalConnector{};
    ar & make_nvp("PhysicalConnector", physicalConnector);

    ::DFL::Mdib::Handles invocationRequested{};
    ar & make_nvp("InvocationRequested", invocationRequested);

    ::DFL::Mdib::Handles invocationRequired{};
    ar & make_nvp("InvocationRequired", invocationRequired);

    ::DFL::Mdib::OperationGroups operationGroups{};
    ar & make_nvp("OperationGroups", operationGroups);

    ::DFL::Mdib::ExtensionTypes extensions{};
    ar & make_nvp("Extensions", extensions);

    ::new(dst) ::DFL::Mdib::ScoState(
        activationState,
        operatingHours,
        operatingCycles,
        calibrationInfo,
        nextCalibrationInfo,
        physicalConnector,
        invocationRequested,
        invocationRequired,
        operationGroups,
        std::move(extensions));
}

/**
 * @brief Support for Boost Serialization.
 * @ingroup Mdib
 */
template<class Archive>
void load(Archive& /*ar*/, ::DFL::Mdib::ScoState& /*dst*/, const unsigned int /*version*/)
{
}

}
}
