/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Operation/SetContextStateOperationState.h>
#include <Framework/Mdib/Public/Model/ExtensionTypeSerialize.h>

#include <boost/serialization/nvp.hpp>
#include <boost/serialization/split_free.hpp>
#include <boost/serialization/version.hpp>
#include <boost/serialization/vector.hpp>

#include <utility>

BOOST_SERIALIZATION_SPLIT_FREE(::DFL::Mdib::SetContextStateOperationState)

BOOST_CLASS_VERSION(::DFL::Mdib::SetContextStateOperationState, 0)

BOOST_CLASS_TRACKING(::DFL::Mdib::SetContextStateOperationState, boost::serialization::track_never)

namespace boost
{
namespace serialization
{
/**
 * @brief Support for Boost Serialization.
 * @ingroup Mdib
 */
template<class Archive>
void save(Archive& ar, const ::DFL::Mdib::SetContextStateOperationState& src, const unsigned int /*fileVersion*/)
{
    const auto& operatingMode = src.operatingMode();
    ar & make_nvp("OperatingMode", operatingMode);

    const auto& extensions = src.extensions();
    ar & make_nvp("Extensions", extensions);
}

/**
 * @brief Support for Boost Serialization.
 * @ingroup Mdib
 */
template<class Archive>
void load_construct_data(Archive& ar, ::DFL::Mdib::SetContextStateOperationState* dst, const unsigned int /*version*/)
{
    ::DFL::Mdib::OperatingMode operatingMode{};
    ar & make_nvp("OperatingMode", operatingMode);

    ::DFL::Mdib::ExtensionTypes extensions{};
    ar & make_nvp("Extensions", extensions);

    ::new(dst) ::DFL::Mdib::SetContextStateOperationState(
        operatingMode,
        std::move(extensions));
}

/**
 * @brief Support for Boost Serialization.
 * @ingroup Mdib
 */
template<class Archive>
void load(Archive& /*ar*/, ::DFL::Mdib::SetContextStateOperationState& /*dst*/, const unsigned int /*version*/)
{
}

}
}
