/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Operation/SetComponentStateOperationState.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param setComponentStateOperationState @ref DFL::Mdib::SetComponentStateOperationState value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const SetComponentStateOperationState& setComponentStateOperationState)
{
    vis(setComponentStateOperationState.operatingMode());
    vis(setComponentStateOperationState.extensions());
}
}
}
}
