/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Operation/SetMetricStateOperationDescriptor.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param setMetricStateOperationDescriptor @ref DFL::Mdib::SetMetricStateOperationDescriptor value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const SetMetricStateOperationDescriptor& setMetricStateOperationDescriptor)
{
    vis(setMetricStateOperationDescriptor.safetyClassification());
    vis(setMetricStateOperationDescriptor.type());
    vis(setMetricStateOperationDescriptor.operationTarget());
    vis(setMetricStateOperationDescriptor.maxTimeToFinish());
    vis(setMetricStateOperationDescriptor.invocationEffectiveTimeout());
    vis(setMetricStateOperationDescriptor.retriggerable());
    vis(setMetricStateOperationDescriptor.accessLevel());
    vis(setMetricStateOperationDescriptor.modifiableData());
    vis(setMetricStateOperationDescriptor.extensions());
}
}
}
}
