/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Operation/SetStringOperationDescriptor.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param setStringOperationDescriptor @ref DFL::Mdib::SetStringOperationDescriptor value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const SetStringOperationDescriptor& setStringOperationDescriptor)
{
    vis(setStringOperationDescriptor.safetyClassification());
    vis(setStringOperationDescriptor.type());
    vis(setStringOperationDescriptor.operationTarget());
    vis(setStringOperationDescriptor.maxTimeToFinish());
    vis(setStringOperationDescriptor.invocationEffectiveTimeout());
    vis(setStringOperationDescriptor.retriggerable());
    vis(setStringOperationDescriptor.accessLevel());
    vis(setStringOperationDescriptor.maxLength());
    vis(setStringOperationDescriptor.extensions());
}
}
}
}
