/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Operation/SetValueOperationState.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param setValueOperationState @ref DFL::Mdib::SetValueOperationState value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const SetValueOperationState& setValueOperationState)
{
    vis(setValueOperationState.operatingMode());
    vis(setValueOperationState.allowedRanges());
    vis(setValueOperationState.extensions());
}
}
}
}
