/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Operation/SetValueOperationDescriptor.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param setValueOperationDescriptor @ref DFL::Mdib::SetValueOperationDescriptor value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const SetValueOperationDescriptor& setValueOperationDescriptor)
{
    vis(setValueOperationDescriptor.safetyClassification());
    vis(setValueOperationDescriptor.type());
    vis(setValueOperationDescriptor.operationTarget());
    vis(setValueOperationDescriptor.maxTimeToFinish());
    vis(setValueOperationDescriptor.invocationEffectiveTimeout());
    vis(setValueOperationDescriptor.retriggerable());
    vis(setValueOperationDescriptor.accessLevel());
    vis(setValueOperationDescriptor.extensions());
}
}
}
}
