/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Metric/EnumStringMetricState.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param enumStringMetricState @ref DFL::Mdib::EnumStringMetricState value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const EnumStringMetricState& enumStringMetricState)
{
    vis(enumStringMetricState.activationState());
    vis(enumStringMetricState.activeDeterminationPeriod());
    vis(enumStringMetricState.lifeTimePeriod());
    vis(enumStringMetricState.bodySites());
    vis(enumStringMetricState.physicalConnector());
    vis(enumStringMetricState.metricValue());
    vis(enumStringMetricState.extensions());
}
}
}
}
