/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Metric/EnumStringMetricDescriptor.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param enumStringMetricDescriptor @ref DFL::Mdib::EnumStringMetricDescriptor value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const EnumStringMetricDescriptor& enumStringMetricDescriptor)
{
    vis(enumStringMetricDescriptor.safetyClassification());
    vis(enumStringMetricDescriptor.type());
    vis(enumStringMetricDescriptor.unit());
    vis(enumStringMetricDescriptor.bodySites());
    vis(enumStringMetricDescriptor.metricCategory());
    vis(enumStringMetricDescriptor.derivationMethod());
    vis(enumStringMetricDescriptor.metricAvailability());
    vis(enumStringMetricDescriptor.maxMeasurementTime());
    vis(enumStringMetricDescriptor.maxDelayTime());
    vis(enumStringMetricDescriptor.determinationPeriod());
    vis(enumStringMetricDescriptor.lifeTimePeriod());
    vis(enumStringMetricDescriptor.activationDuration());
    vis(enumStringMetricDescriptor.relations());
    vis(enumStringMetricDescriptor.allowedValues());
    vis(enumStringMetricDescriptor.extensions());
}
}
}
}
