/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Metric/MetricQuality.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param metricQuality @ref DFL::Mdib::MetricQuality value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const MetricQuality& metricQuality)
{
    vis(metricQuality.validity());
    vis(metricQuality.mode());
    vis(metricQuality.qualityIndicator());
    vis(metricQuality.extensions());
}
}
}
}
