/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Metric/NumericMetricState.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param numericMetricState @ref DFL::Mdib::NumericMetricState value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const NumericMetricState& numericMetricState)
{
    vis(numericMetricState.activationState());
    vis(numericMetricState.activeDeterminationPeriod());
    vis(numericMetricState.lifeTimePeriod());
    vis(numericMetricState.bodySites());
    vis(numericMetricState.physicalConnector());
    vis(numericMetricState.activeAveragingPeriod());
    vis(numericMetricState.metricValue());
    vis(numericMetricState.physiologicalRanges());
    vis(numericMetricState.extensions());
}
}
}
}
