/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Metric/RealTimeSampleArrayMetricState.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param realTimeSampleArrayMetricState @ref DFL::Mdib::RealTimeSampleArrayMetricState value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const RealTimeSampleArrayMetricState& realTimeSampleArrayMetricState)
{
    vis(realTimeSampleArrayMetricState.activationState());
    vis(realTimeSampleArrayMetricState.activeDeterminationPeriod());
    vis(realTimeSampleArrayMetricState.lifeTimePeriod());
    vis(realTimeSampleArrayMetricState.bodySites());
    vis(realTimeSampleArrayMetricState.physicalConnector());
    vis(realTimeSampleArrayMetricState.metricValue());
    vis(realTimeSampleArrayMetricState.physiologicalRanges());
    vis(realTimeSampleArrayMetricState.extensions());
}
}
}
}
