/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Metric/SampleArrayValue.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param sampleArrayValue @ref DFL::Mdib::SampleArrayValue value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const SampleArrayValue& sampleArrayValue)
{
    vis(sampleArrayValue.metricQuality());
    vis(sampleArrayValue.annotations());
    vis(sampleArrayValue.startTime());
    vis(sampleArrayValue.stopTime());
    vis(sampleArrayValue.determinationTime());
    vis(sampleArrayValue.samples());
    vis(sampleArrayValue.extensions());
}
}
}
}
