/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Metric/StringMetricValue.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param stringMetricValue @ref DFL::Mdib::StringMetricValue value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const StringMetricValue& stringMetricValue)
{
    vis(stringMetricValue.metricQuality());
    vis(stringMetricValue.annotations());
    vis(stringMetricValue.startTime());
    vis(stringMetricValue.stopTime());
    vis(stringMetricValue.determinationTime());
    vis(stringMetricValue.value());
    vis(stringMetricValue.extensions());
}
}
}
}
