/**************************************************************************************
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * THIS FILE IS GENERATED BY
 * modules\S32\Tools\MdibBuilders\RunGenerator.cmd
 *
 **************************************************************************************/

#pragma once

#include <Framework/Mdib/Public/Model/Metric/StringMetricDescriptor.h>

namespace DFL
{
namespace Mdib
{
namespace Impl
{
/**
 * @brief Calls the visitor for each member.
 *
 * @param vis visitor
 * @param stringMetricDescriptor @ref DFL::Mdib::StringMetricDescriptor value to visit
 * @ingroup Mdib
 */
template <class Visitor>
void visitMembers(Visitor& vis, const StringMetricDescriptor& stringMetricDescriptor)
{
    vis(stringMetricDescriptor.safetyClassification());
    vis(stringMetricDescriptor.type());
    vis(stringMetricDescriptor.unit());
    vis(stringMetricDescriptor.bodySites());
    vis(stringMetricDescriptor.metricCategory());
    vis(stringMetricDescriptor.derivationMethod());
    vis(stringMetricDescriptor.metricAvailability());
    vis(stringMetricDescriptor.maxMeasurementTime());
    vis(stringMetricDescriptor.maxDelayTime());
    vis(stringMetricDescriptor.determinationPeriod());
    vis(stringMetricDescriptor.lifeTimePeriod());
    vis(stringMetricDescriptor.activationDuration());
    vis(stringMetricDescriptor.relations());
    vis(stringMetricDescriptor.extensions());
}
}
}
}
